# Generated by Django 4.1.7 on 2023-02-22 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Businessunit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=20, null=True)),
                ('category', models.CharField(max_length=20, null=True)),
                ('company', models.CharField(max_length=20)),
                ('description', models.TimeField(max_length=500, null=True)),
                ('started_on', models.DateField()),
                ('country', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100, null=True)),
                ('city', models.CharField(max_length=100)),
                ('street_adress_1', models.TextField(max_length=500, null=True)),
                ('street_adress_2', models.TextField(max_length=500, null=True)),
            ],
        ),
    ]
