# Generated by Django 4.1.7 on 2023-02-22 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100, null=True)),
                ('city', models.CharField(max_length=100)),
                ('street_adress_1', models.TextField(max_length=500, null=True)),
                ('street_adress_2', models.TextField(max_length=500, null=True)),
            ],
        ),
    ]
