# Generated by Django 4.1.7 on 2023-02-22 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0002_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('employee_id', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100, null=True)),
                ('Role', models.CharField(max_length=100)),
                ('b_unit', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('reporting_manager', models.TextField(max_length=500, null=True)),
                ('date_of_joining', models.TextField(max_length=500, null=True)),
            ],
        ),
    ]
