# Generated by Django 4.1.7 on 2023-02-22 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0003_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessunit',
            name='description',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
