# Generated by Django 4.1.7 on 2023-02-22 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0004_alter_businessunit_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('b_unit', models.CharField(max_length=20, null=True)),
                ('head_of_department', models.CharField(max_length=20, null=True)),
                ('manager', models.CharField(max_length=20)),
                ('description', models.TimeField(max_length=500, null=True)),
            ],
        ),
    ]
