# Generated by Django 4.1.7 on 2023-02-22 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0005_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.IntegerField(blank=True, null=True)),
                ('sub_category', models.IntegerField(blank=True, null=True)),
                ('company_asset_code', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=15)),
                ('allocated_to', models.IntegerField(blank=True, null=True)),
                ('responsible_technician', models.IntegerField(blank=True, null=True)),
                ('vendor', models.IntegerField(blank=True, null=True)),
                ('asset_classification', models.CharField(max_length=50)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('invoice_number', models.CharField(blank=True, max_length=50, null=True)),
                ('manufacturer', models.CharField(max_length=50)),
                ('key_number', models.CharField(max_length=11)),
                ('warenty_status', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('warenty_end_date', models.DateField(blank=True, null=True)),
                ('is_working', models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], max_length=3)),
                ('notes', models.TextField(blank=True, null=True)),
                ('image', models.TextField(blank=True, null=True)),
                ('imagencrpname', models.TextField()),
                ('qr_image', models.TextField()),
                ('isactive', models.BooleanField(blank=True, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('modified_by', models.IntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'assets',
            },
        ),
        migrations.CreateModel(
            name='AssetsHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_id', models.IntegerField(blank=True, null=True)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('history', models.CharField(blank=True, max_length=500, null=True)),
                ('isactive', models.BooleanField(blank=True, null=True)),
                ('createdby', models.IntegerField(blank=True, null=True)),
                ('modifiedby', models.IntegerField(blank=True, null=True)),
                ('createddate', models.DateTimeField(blank=True, null=True)),
                ('modifieddate', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'assets_history',
            },
        ),
        migrations.CreateModel(
            name='AssetsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(blank=True, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('modified_by', models.CharField(blank=True, max_length=11, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(blank=True, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hrms.assetscategory')),
            ],
            options={
                'db_table': 'assets_categories',
            },
        ),
    ]
