# Generated by Django 4.1.7 on 2023-02-22 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0008_remove_employee_first_name_remove_employee_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='reporting_manager',
            field=models.CharField(choices=[], max_length=100),
        ),
    ]
